travis:
  secure:
    BINSTAR_TOKEN: HCGBMg5ruz9FGuL7vuzA5et6bm1qAH5XmdS2XRPVcrt7GWs0McDOUdaEuEoEqGCkmc6I/yPlIfpuWt5R5MdnLP4YnKmLTmk+yFNba5S4oayLsL8avHdZF5wiKk4zosSFsw4DRXdGi5XCqLcr3dL2qszYrJ0NoOx4hPaQthY6l5yJkQvGwULXwgo4yuhnLTwnhJB2lz50Z9LTiV35h9oAWPxPa34eD0ASHOplsaNb8llF1oPimIVMIEmgHeKCB2vqPdV7BxgHz+u9HLnRw5AmBi8v2jwRGffrQdJ8atnkIW1CpH3wrDXFsA2iH9E6aNhUBud6A++hfT73jOl3UAyTVXDF8hoFEYZBxWZdWXAd8DtHTtkaEy5mdrgXprtzvecHhYf7m9AZPmIYH1ZXWKeOVHH7w2lgB+DZXUet+s1MPshUe85p5mCfD1evD7/XnqTC295cVHPR9+sfpwhhoAdpNEVIBUVr2t8rq18nEuUiShv0l3i2KF2Uhe1iMBmzXjFoTH0kiJgm+dc8qkAMSZnH9r9VVlvGXOqasSjm1bKityjYjCPBIS/BWz/MdbwznBbz86OA9buB3tcwlErA77Nwfse92PzOAEIfNaPssl0NxgBLeHDdRJ8K9VOCxULRzx1Q6yI96u2UJHE6MWPeoMOsCzQC+mI98IXq9RKJ/cldFw4=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
