travis:
  secure:
    BINSTAR_TOKEN: HQbj7lACQ0gT+b+TT2jj5z4ilNeZMtn2c/ziYm1McTdeaGxmOQtmszeXyvpm3bb73owDyVZBXwkHP+tjApcWDtt1pCoNM6wDggrXMysd9sgvKGW/JJ4bMR1WlNQmCU05E+Fb/9aEuCbTl5v5uaO+WiCb/zuVzY4fZsKx2PBPtb7Z2IBUDjuYavh1eHdb83Y9y72+Mtc+L9mdqbjAv9EfzNoACc7JY2+JoFOrEmsRw5PH3+4UTlOn/CP+9DeKBWYnbdVW8zqIItralTQyRh05lz6Al5enQTySJA3CZKnKFa2d8QyqLxAXNlcP8VWhSZCxRY/GeTI3N6aGCtocoF57XRwxDore78k27BXGfE8IX41If4nMpo2Ek97q3lXxHA0yjLpuWhsvLpo73TlFKK1ip7psGu9C7V4q9oKY2KU+HNurz/HIRVLX5lDLx/K2LxapmrJF6SDY2CSYDGWfgCAUpoNSqoQCN6Z9AqpHTvLyL+vREMCE8k50788N/ikw5XQkE5ZGzpUY1bxSymxUX/uz5reCX+cwwr0/EC0eNIS3zjJB3UMEOg4JNjYvmODf3x3v9X1gRUEbkD4Tw4j3nMXQ2QkONZQvl37l5H4KBnOIaIj3lujt2zb8VfaqQOnJPW8/0cgI+JslVLu6H/a367AX36a5spHOZGOQbFtl5X5Vgx0=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
provider:
  win: azure
conda_forge_output_validation: true
